CHANGED: Docker compose web container to test entrypoint.

diff --git a/docker-compose.yml b/docker-compose.yml
--- a/docker-compose.yml
+++ b/docker-compose.yml
@@ -331,7 +331,63 @@ services:
       - SENTRY_DB_PASSWORD=${DB_PASSWORD}
       - SENTRY_DB_HOST=${DB_HOST}
       - SENTRY_DB_PORT=${DB_PORT}
-    entrypoint: ./postgres/postgres-entrypoint.sh
+    entrypoint: #./postgres/postgres-entrypoint.sh
+      - |  
+        #!/bin/bash
+        set -e
+  
+        prep_init_db() {
+        cp /opt/sentry/init_hba.sh /docker-entrypoint-initdb.d/init_hba.sh
+        }
+  
+        cdc_setup_hba_conf() {
+        # Ensure pg-hba is properly configured to allow connections
+        # to the replication slots.
+        
+        PG_HBA="$PGDATA/pg_hba.conf"
+        if [ ! -f "$PG_HBA" ]; then
+        echo "DB not initialized. Postgres will take care of pg_hba"
+        elif [ "$(grep -c -E "^host\s+replication" "$PGDATA"/pg_hba.conf)" != 0 ]; then
+        echo "Replication config already present in pg_hba. Not changing anything."
+        else
+        # Execute the same script we run on DB initialization
+        /opt/sentry/init_hba.sh
+        fi
+        }
+  
+        bind_wal2json() {
+        # Copy the file in the right place
+        cp /opt/sentry/wal2json/wal2json.so $(pg_config --pkglibdir)/wal2json.so
+        }
+  
+        echo "Setting up Change Data Capture"
+  
+        prep_init_db
+        if [ "$1" = 'postgres' ]; then
+        cdc_setup_hba_conf
+        bind_wal2json
+        fi
+  
+        # Set environment variables for PostgreSQL client
+        export PGPASSWORD=$SENTRY_DB_PASSWORD
+  
+        # Ensure the container connects to the RDS database
+        echo "Connecting to the external PostgreSQL database..."
+  
+        RETRIES=5
+        until psql -h $SENTRY_DB_HOST -U $SENTRY_DB_USER -d $SENTRY_DB_NAME -c "select 1" >/dev/null 2>&1 || [ $RETRIES -eq 0 ]; do
+        echo "Waiting for postgres server, $((RETRIES--)) remaining attempts..."
+        sleep 1
+        done
+  
+        if [ $RETRIES -eq 0 ]; then
+        echo "Failed to connect to PostgreSQL database at $SENTRY_DB_HOST"
+        exit 1
+        fi
+  
+        echo "Connected to the PostgreSQL database at $SENTRY_DB_HOST"
+  
+        exec /usr/local/bin/docker-entrypoint.sh "$@"
     ulimits:
       nofile:
         soft: 4096
