WIP: Web cotainer entrypoint script corrected.

diff --git a/docker-compose.yml b/docker-compose.yml
--- a/docker-compose.yml
+++ b/docker-compose.yml
@@ -337,32 +337,63 @@ services:
       - -c
       - |
         _group="Ensuring proper PostgreSQL version ..."
-        
+
         echo "${_group}"
-        
+
         # Wait for the external PostgreSQL database to be ready
         RETRIES=5
-        until PGPASSWORD="SENTRY_DB_PASSWORD" psql -h "$DB_HOST" -U "SENTRY_DB_USER" -d "$SENTRY_DB_NAME" -c "select 1" >/dev/null 2>&1 || [ $RETRIES -eq 0 ]; do
-          echo "Waiting for PostgreSQL server at $SENTRY_DB_HOST:SENTRY_DB_PORT, $((RETRIES--)) remaining attempts..."
+        until PGPASSWORD="$SENTRY_DB_PASSWORD" psql -h "$SENTRY_DB_HOST" -U "$SENTRY_DB_USER" -d "$SENTRY_DB_NAME" -c "select 1" >/dev/null 2>&1 || [ "$RETRIES" -eq 0 ]; do
+          echo "Waiting for PostgreSQL server at $SENTRY_DB_HOST:$SENTRY_DB_PORT, $RETRIES remaining attempts..."
+          RETRIES=$(expr $RETRIES - 1)
           sleep 1
         done
-        
-        if [ $RETRIES -eq 0 ]; then
-          echo "Failed to connect to PostgreSQL server at $SENTRY_DB_HOST:SENTRY_DB_PORT. Exiting."
+
+        if [ "$RETRIES" -eq 0 ]; then
+          echo "Failed to connect to PostgreSQL server at $SENTRY_DB_HOST:$SENTRY_DB_PORT. Exiting."
           exit 1
         fi
-        
+
         echo "Re-indexing due to glibc change, this may take a while..."
-        
+
         # Reindex all databases and their system catalogs which are not templates
-        DBS=$(PGPASSWORD=SENTRY_DB_PASSWORD psql -h $SENTRY_DB_HOST -U $SENTRY_DB_USER -d postgres -t -c "SELECT datname FROM pg_database WHERE datistemplate = false;" | xargs)
+        DBS=$(PGPASSWORD="$SENTRY_DB_PASSWORD" psql -h "$SENTRY_DB_HOST" -U "$SENTRY_DB_USER" -d postgres -t -c "SELECT datname FROM pg_database WHERE datistemplate = false;" | xargs)
         for db in ${DBS}; do
           echo "Re-indexing database: ${db}"
-          PGPASSWORD=$SENTRY_DB_PASSWORD psql -h $SENTRY_DB_HOST -U $SENTRY_DB_USER -d ${db} -c "REINDEX SYSTEM ${db};"
-          PGPASSWORD=$SENTRY_DB_PASSWORD psql -h $SENTRY_DB_HOST -U $SENTRY_DB_USER -d ${db} -c "REINDEX DATABASE ${db};"
+          PGPASSWORD="$SENTRY_DB_PASSWORD" psql -h "$SENTRY_DB_HOST" -U "$SENTRY_DB_USER" -d ${db} -c "REINDEX SYSTEM ${db};"
+          PGPASSWORD="$SENTRY_DB_PASSWORD" psql -h "$SENTRY_DB_HOST" -U "$SENTRY_DB_USER" -d ${db} -c "REINDEX DATABASE ${db};"
         done
-        
+
         echo "${_endgroup}"
+#      - /bin/sh
+#      - -c
+#      - |
+#        _group="Ensuring proper PostgreSQL version ..."
+#
+#        echo "${_group}"
+#
+#        # Wait for the external PostgreSQL database to be ready
+#        RETRIES=5
+#        until PGPASSWORD="SENTRY_DB_PASSWORD" psql -h "$DB_HOST" -U "SENTRY_DB_USER" -d "$SENTRY_DB_NAME" -c "select 1" >/dev/null 2>&1 || [ $RETRIES -eq 0 ]; do
+#          echo "Waiting for PostgreSQL server at $SENTRY_DB_HOST:SENTRY_DB_PORT, $((RETRIES--)) remaining attempts..."
+#          sleep 1
+#        done
+#
+#        if [ $RETRIES -eq 0 ]; then
+#          echo "Failed to connect to PostgreSQL server at $SENTRY_DB_HOST:SENTRY_DB_PORT. Exiting."
+#          exit 1
+#        fi
+#
+#        echo "Re-indexing due to glibc change, this may take a while..."
+#
+#        # Reindex all databases and their system catalogs which are not templates
+#        DBS=$(PGPASSWORD=SENTRY_DB_PASSWORD psql -h $SENTRY_DB_HOST -U $SENTRY_DB_USER -d postgres -t -c "SELECT datname FROM pg_database WHERE datistemplate = false;" | xargs)
+#        for db in ${DBS}; do
+#          echo "Re-indexing database: ${db}"
+#          PGPASSWORD=$SENTRY_DB_PASSWORD psql -h $SENTRY_DB_HOST -U $SENTRY_DB_USER -d ${db} -c "REINDEX SYSTEM ${db};"
+#          PGPASSWORD=$SENTRY_DB_PASSWORD psql -h $SENTRY_DB_HOST -U $SENTRY_DB_USER -d ${db} -c "REINDEX DATABASE ${db};"
+#        done
+#
+#        echo "${_endgroup}"
     ulimits:
       nofile:
         soft: 4096
